CREATE TABLE  "BOOK"
   (    
    "BOOKID" VARCHAR2(4000),
    "NAME" VARCHAR2(4000),
    "AUTHOR" VARCHAR2(4000),
    "PUBLISHER" VARCHAR2(4000),
    "ISSUED" NUMBER,
    "IMAGE" VARCHAR(4000),
     CONSTRAINT "E_BOOK_PK" PRIMARY KEY ("BOOKID") ENABLE
   );

CREATE TABLE  "LIBRARIAN"
   (    
    "ID" NUMBER,
    "NAME" VARCHAR2(4000),
    "PASSWORD" VARCHAR2(4000),
    "EMAIL" VARCHAR2(4000),
    "MOBILE" NUMBER,
     CONSTRAINT "E_LIBRARIAN_PK" PRIMARY KEY ("ID") ENABLE
   );
       
CREATE TABLE  "ISSUEBOOK"
   (    
    "BOOKID" VARCHAR2(4000) NOT NULL ENABLE,
    "STUDENTID" VARCHAR2(4000) NOT NULL ENABLE,
    "STUDENTNAME" VARCHAR2(4000),
    "STUDENTMOBILE" NUMBER,
    "ISSUEDDATE" DATE,
    "RETURNSTATUS" VARCHAR2(4000)
   );

    
